#!/bin/bash 
if ! [[ -f yarn.lock ]]; then 
    echo "You are either not running in the root directory of your project, or you have not yet build the static files. Run \"yarn build\" to build the static code for the project, and try again."
    exit 1
fi
# All set!
cp -v public/index.ghpages.html public/index.html &&\
yarn build &&\
rm -Rf docs && mv -v build docs &&\
cp -v public/index.standalone.html public/index.html &&\
git add --all &&\
git commit -m "Pushing update to github pages" &&\
git push